from backbone import *
from utils import cfg

preset = {
        'm0':
        ['MODEL.MICRONETS.BLOCK', 'DYMicroBlock', 'MODEL.MICRONETS.NET_CONFIG', 'msnx_dy6_exp4_4M_221', 'MODEL.MICRONETS.STEM_CH', '4', 'MODEL.MICRONETS.STEM_GROUPS', '2,2', 'MODEL.MICRONETS.STEM_DILATION', '1', 'MODEL.MICRONETS.STEM_MODE', 'spatialsepsf', 'MODEL.MICRONETS.OUT_CH', '640', 'MODEL.MICRONETS.DEPTHSEP', 'True', 'MODEL.MICRONETS.POINTWISE', 'group', 'MODEL.MICRONETS.DROPOUT', '0.05', 'MODEL.ACTIVATION.MODULE', 'DYShiftMax', 'MODEL.ACTIVATION.ACT_MAX', '2.0', 'MODEL.ACTIVATION.LINEARSE_BIAS', 'False', 'MODEL.ACTIVATION.INIT_A_BLOCK3', '1.0,0.0', 'MODEL.ACTIVATION.INIT_A', '1.0,1.0', 'MODEL.ACTIVATION.INIT_B', '0.0,0.0', 'MODEL.ACTIVATION.REDUCTION', '8', 'MODEL.MICRONETS.SHUFFLE', 'True'],
        'm1':
        ['MODEL.MICRONETS.BLOCK', 'DYMicroBlock', 'MODEL.MICRONETS.NET_CONFIG', 'msnx_dy6_exp6_6M_221', 'MODEL.MICRONETS.STEM_CH', '6', 'MODEL.MICRONETS.STEM_GROUPS', '3,2', 'MODEL.MICRONETS.STEM_DILATION', '1', 'MODEL.MICRONETS.STEM_MODE', 'spatialsepsf', 'MODEL.MICRONETS.OUT_CH', '960', 'MODEL.MICRONETS.DEPTHSEP', 'True', 'MODEL.MICRONETS.POINTWISE', 'group', 'MODEL.MICRONETS.DROPOUT', '0.05', 'MODEL.ACTIVATION.MODULE', 'DYShiftMax', 'MODEL.ACTIVATION.ACT_MAX', '2.0', 'MODEL.ACTIVATION.LINEARSE_BIAS', 'False', 'MODEL.ACTIVATION.INIT_A_BLOCK3', '1.0,0.0', 'MODEL.ACTIVATION.INIT_A', '1.0,1.0', 'MODEL.ACTIVATION.INIT_B', '0.0,0.0', 'MODEL.ACTIVATION.REDUCTION', '8', 'MODEL.MICRONETS.SHUFFLE', 'True'],
        'm2':
        ['MODEL.MICRONETS.BLOCK', 'DYMicroBlock', 'MODEL.MICRONETS.NET_CONFIG', 'msnx_dy9_exp6_12M_221', 'MODEL.MICRONETS.STEM_CH', '8', 'MODEL.MICRONETS.STEM_GROUPS', '4,2', 'MODEL.MICRONETS.STEM_DILATION', '1', 'MODEL.MICRONETS.STEM_MODE', 'spatialsepsf', 'MODEL.MICRONETS.OUT_CH', '1024', 'MODEL.MICRONETS.DEPTHSEP', 'True', 'MODEL.MICRONETS.POINTWISE', 'group', 'MODEL.MICRONETS.DROPOUT', '0.1', 'MODEL.ACTIVATION.MODULE', 'DYShiftMax', 'MODEL.ACTIVATION.ACT_MAX', '2.0', 'MODEL.ACTIVATION.LINEARSE_BIAS', 'False', 'MODEL.ACTIVATION.INIT_A_BLOCK3', '1.0,0.0', 'MODEL.ACTIVATION.INIT_A', '1.0,1.0', 'MODEL.ACTIVATION.INIT_B', '0.0,0.0', 'MODEL.ACTIVATION.REDUCTION', '8', 'MODEL.MICRONETS.SHUFFLE', 'True'],
        'm3':
        ['MODEL.MICRONETS.BLOCK', 'DYMicroBlock', 'MODEL.MICRONETS.NET_CONFIG', 'msnx_dy12_exp6_20M_020', 'MODEL.MICRONETS.STEM_CH', '12', 'MODEL.MICRONETS.STEM_GROUPS', '4,3', 'MODEL.MICRONETS.STEM_DILATION', '1', 'MODEL.MICRONETS.STEM_MODE', 'spatialsepsf', 'MODEL.MICRONETS.OUT_CH', '1024', 'MODEL.MICRONETS.DEPTHSEP', 'True', 'MODEL.MICRONETS.POINTWISE', 'group', 'MODEL.MICRONETS.DROPOUT', '0.1', 'MODEL.ACTIVATION.MODULE', 'DYShiftMax', 'MODEL.ACTIVATION.ACT_MAX', '2.0', 'MODEL.ACTIVATION.LINEARSE_BIAS', 'False', 'MODEL.ACTIVATION.INIT_A_BLOCK3', '1.0,0.0', 'MODEL.ACTIVATION.INIT_A', '1.0,0.5', 'MODEL.ACTIVATION.INIT_B', '0.0,0.5', 'MODEL.ACTIVATION.REDUCTION', '8', 'MODEL.MICRONETS.SHUFFLE', 'True']
        }

def micronet(name='m0'):
    cfg.merge_from_list(preset[name])
    return eval('MicroNet')(cfg)



